### Create user
POST http://localhost:3333/user
Content-Type: application/json

{
	"name": "Andrew Moreira",
	"email": "andrewmoreira@gmail.com",
	"password": "123456"
}

### Login Route
POST http://localhost:3333/login
Content-Type: application/json

{
	"email": "andrewmoreira@gmai",
	"password": "1234"
}

### Start Session Route
POST http://localhost:3333/start-session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNDg0M2RmNC02ZmM4LTQ4MTktOWViOS05M2FiYTQxNzJjMTIiLCJpYXQiOjE3NDU3OTY0NDUsImV4cCI6MTc0ODM4ODQ0NX0.qEknbKnkS0S63PXJb76iMSkOSDKqIrUHBeD6g1s5oV0

{
	"type": "shortBreak"
}


### End Session Route
PUT http://localhost:3333/end-session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNDg0M2RmNC02ZmM4LTQ4MTktOWViOS05M2FiYTQxNzJjMTIiLCJpYXQiOjE3NDU3OTY0NDUsImV4cCI6MTc0ODM4ODQ0NX0.qEknbKnkS0S63PXJb76iMSkOSDKqIrUHBeD6g1s5oV0

{
	"duration": 1547,
	"sessionId": "eabaf8e0-4142-474e-9925-017a63ea1dc6"
}

### Get Sessions Data Progress Route
GET http://localhost:3333/get-data-progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNDg0M2RmNC02ZmM4LTQ4MTktOWViOS05M2FiYTQxNzJjMTIiLCJpYXQiOjE3NDU3OTY0NDUsImV4cCI6MTc0ODM4ODQ0NX0.qEknbKnkS0S63PXJb76iMSkOSDKqIrUHBeD6g1s5oV0

### Get Sessions Data Statistics Route
GET http://localhost:3333/get-data-statistic?daysPrevious=7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNDg0M2RmNC02ZmM4LTQ4MTktOWViOS05M2FiYTQxNzJjMTIiLCJpYXQiOjE3NDU3OTY0NDUsImV4cCI6MTc0ODM4ODQ0NX0.qEknbKnkS0S63PXJb76iMSkOSDKqIrUHBeD6g1s5oV

### Create Task Route
POST http://localhost:3333/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNDg0M2RmNC02ZmM4LTQ4MTktOWViOS05M2FiYTQxNzJjMTIiLCJpYXQiOjE3NDU3OTY0NDUsImV4cCI6MTc0ODM4ODQ0NX0.qEknbKnkS0S63PXJb76iMSkOSDKqIrUHBeD6g1s5oV0

{
	"title": "Create a new task",
}