### Create user
POST http://localhost:3000/user
Content-Type: application/json

{
	"name": "Andrew Moreira",
	"email": "andrew@gmail.com",
	"password": "123456"
}

### Login Route
POST http://localhost:3000/login
Content-Type: application/json

{
	"email": "andrew@gmail.com",
	"password": "123456"
}

### Start Session Route
POST http://localhost:3000/start-session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiYzc3NWVlNi1mOTdlLTQyZjMtOTgwNy0yMGQ0MzA4NjU4NTQiLCJpYXQiOjE3NDUyNzIyODEsImV4cCI6MTc0Nzg2NDI4MX0.FXOhNFdVy0inlC4wGodS6BuV_eFZvMOL2-kSHVhMtQY

{
	"type": "focus"
}


### End Session Route
PUT http://localhost:3000/end-session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiYzc3NWVlNi1mOTdlLTQyZjMtOTgwNy0yMGQ0MzA4NjU4NTQiLCJpYXQiOjE3NDUyNzIyODEsImV4cCI6MTc0Nzg2NDI4MX0.FXOhNFdVy0inlC4wGodS6BuV_eFZvMOL2-kSHVhMtQY

{
	"duration": 1547,
	"sessionId": "b8164b3e-a7e3-42fe-89d3-940201148977"
}

### Get Sessions Data Progress Route
GET http://localhost:3000/get-data-progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiYzc3NWVlNi1mOTdlLTQyZjMtOTgwNy0yMGQ0MzA4NjU4NTQiLCJpYXQiOjE3NDUyNzIyODEsImV4cCI6MTc0Nzg2NDI4MX0.FXOhNFdVy0inlC4wGodS6BuV_eFZvMOL2-kSHVhMtQY

### Get Sessions Data Statistics Route
GET http://localhost:3000/get-data-statistic?daysPrevious=7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiYzc3NWVlNi1mOTdlLTQyZjMtOTgwNy0yMGQ0MzA4NjU4NTQiLCJpYXQiOjE3NDUyNzIyODEsImV4cCI6MTc0Nzg2NDI4MX0.FXOhNFdVy0inlC4wGodS6BuV_eFZvMOL2-kSHVhMtQY

### Teste Route
POST http://localhost:3000/teste
Content-Type: application/json

{
	"duration": 1547,
	"sessionId": "15ad7976-414f-4cf8-9db2-5c64317438e1"
}